apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-d
  labels:
      app: myapp
      type: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: sre
      labels:
        app: myapp
    spec:
      containers:
        - name: frontend
          image: abdoman/frontend
          #imagePullPolicy: Never
          ports:
          - containerPort: 3000
        - name: backend
          image: abdoman/backend
          #imagePullPolicy: Never
          ports:
          - containerPort: 4000



